[workspace]

members = [
	"phenix_core",
	"phenix_test",
	"extensions/phenix_html",
	"extensions/phenix_npm",
	"extensions/phenix_git",
	"extensions/phenix_std",
	"extensions/phenix_svelte",
	"extensions/phenix_xml",
	"general/nom_more"
]
