[package]
name = "phenix_svelte"
version = "0.1.0"
edition = "2021"

[dependencies]
phenix_core = { path= "../../phenix_core" }
phenix_npm = { path= "../phenix_npm" }
phenix_html = { path= "../phenix_html" }
phenix_xml = { path= "../phenix_xml" }
const-str = "0.5.4"
