[package]
name = "phenix_html"
version = "0.1.0"
edition = "2021"

[dependencies]
phenix_core = { path="../../phenix_core" }
phenix_prelude = { path="../../phenix_prelude" }
phenix_xml = { path="../phenix_xml" }
